name: Update DockerHub READMEs

on:
  push:
    branches:
      - branch-*
    paths:
      - dockerhub-readme/
      - .github/workflows/dockerhub-readme.yml

jobs:
  readme:
    runs-on: ubuntu-latest
    strategy: matrix
      repo_name:
        - rapidsai
        - rapidsai-dev
        - rapidsai-nightly
        - rapidsai-dev-nightly
        - rapidsai-core
        - rapidsai-core-dev
        - rapidsai-core-nightly
        - rapidsai-core-dev-nightly
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Docker Hub Description >>> ${{ matrix.repo_name }}
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository:  rapidsai/${{ matrix.repo_name }}
          readme-filepath: dockerhub-readme/Dockerhub_${{ matrix.repo_name }}.md
